//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenamientos_x_Usuarios
    {
        public int id { get; set; }
        public int usuario { get; set; }
        public int entrenamiento { get; set; }
    
        public virtual Entrenamiento Entrenamiento1 { get; set; }
    }
}
